name: Release
on:
  push:
    branches:
      - '+([0-9])?(.{+([0-9]),x}).x'
      - main
      - next
      - next-major
      - beta
      - alpha
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test
      - name: Build typescript
        run: npm run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release
